apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docspell-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: docspell.example.com
      http:
        paths:
          - path: /restserver(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: docspell-restserver
                port:
                  name: http
          - path: /joex(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: docspell-joex
                port:
                  name: http
          - path: /solr(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: docspell-solr
                port:
                  name: solr
