apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: docspell
namespace: docspell
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- postgres.yaml
- solr.yaml
configMapGenerator:
- literals:
  - DOCSPELL_SERVER_BACKEND_JDBC_USER=dbuser
  name: restserver-config
- literals:
  - DOCSPELL_JOEX_JDBC_USER=dbuser
  name: joex-config
secretGenerator:
- literals:
  - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=dbpass
  - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=admin123
  - DOCSPELL_SERVER_AUTH_SERVER__SECRET=mysecret
  - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=integration-password123
  - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=myinvitepass
  name: restserver-secrets
- literals:
  - DOCSPELL_JOEX_JDBC_PASSWORD=dbpass
  name: joex-secrets
images:
  - name: docspell/restserver
    newTag: latest
  - name: docspell/joex
    newTag: latest
  - name: docspell/dsc
    newTag: latest
